# Generated by Django 4.2.2 on 2023-07-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_date',
        ),
    ]
