# Generated by Django 4.2.2 on 2023-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_counted_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='counted_views',
            field=models.IntegerField(default=7),
        ),
    ]
