# Generated by Django 4.2.2 on 2023-07-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count_comment',
            field=models.IntegerField(default=0),
        ),
    ]
